### ISSUE TITLE
Ganache Accounts are not Loading

### ISSUE THREAD

**Issue by shikhar229169** [trufflesuite/ganache-ui#5256]
![Screenshot (64)](https://user-images.githubusercontent.com/111875681/219421531-785dbfd0-461c-46a6-8b7f-eded286f6fb0.png)

When I Click on Quick Start, the above attached page opens and I'm stuck here, not able to go to Accounts section.
Please provide a fix for this. 
I don't know why is this happening because earlier the quick start directly loads the account section.

**Comment by jeffsmale90** [comment]
@shikhar229169 thanks for raising this issue! We have a beta release [2.7.0-beta](https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.0-beta) out, can you please install this version and let us know if the issue is resolved?

We are aiming to release this as stable in the next week or so.

Thanks!

**Comment by shikhar229169** [comment]
@jeffsmale90  Thanks for the update.
Yes, this release works and finally the accounts loaded.
Thanks.
